---
- name: install packages
  apt:
    name:
      - libpam-google-authenticator
    update_cache: yes

- name: modify pam config
  lineinfile:
    path: /etc/pam.d/sshd
    insertafter: '^@include common-password$'
    line: 'auth required pam_google_authenticator.so nullok'
  notify: restart sshd

- name: modify sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^KbdInteractiveAuthentication\s'
    line: 'KbdInteractiveAuthentication yes'
  notify: restart sshd

- name: add sshd_config file
  copy:
    src: "{{ item }}"
    dest: /etc/ssh/sshd_config.d/
  with_fileglob:
    - etc/ssh/sshd_config.d/*.conf
  notify: restart sshd
